### PR TITLE
feat(): release @next

### PR DESCRIPTION
**Pull request by rdlabo**
## Try to use

```bash
% npm i @capacitor-community/stripe@next
% npm i @capacitor-community/stripe-identity@next
% npm i @capacitor-community/stripe-terminal@next
```

## Issues

- close https://github.com/capacitor-community/stripe/issues/406
- close https://github.com/capacitor-community/stripe/issues/407
- close https://github.com/capacitor-community/stripe/issues/410

## Note

- remove `stripeterminalLocalmobileVersion` and add to `stripeterminalTapToPayVersion`.

### CODE REVIEW

**Comment by AshleyMedway** [comment]
If you produce a (next) package I am happy to test this today :)

**Comment by rdlabo** [comment]
> If you produce a (next) package I am happy to test this today :)

Thanks. It will be ready within the next hour!

**Comment by rdlabo** [comment]
Released at `next` tag:

```bash
% npm i @capacitor-community/stripe@next
% npm i @capacitor-community/stripe-identity@next
% npm i @capacitor-community/stripe-terminal@next
```

**Comment by AshleyMedway** [comment]
You might want to add to the readme section for iOS that in app podfile you need to update platform to 14 as minimum

```
platform :ios, '14.0'
```

**Comment by AshleyMedway** [comment]
I have tested tap to pay on android and ios all is working well. Thats my only use case at the moment though unfortunately.

**Comment by rdlabo** [comment]
> You might want to add to the readme section for iOS that in app podfile you need to update platform to 14 as minimum
> 
> ```
> platform :ios, '14.0'
> ```

Updated!: https://github.com/capacitor-community/stripe/pull/411/commits/5ca9519a690eedf704737a66b5067e3c029294e0

**Comment by rdlabo** [comment]
> I have tested tap to pay on android and ios all is working well. Thats my only use case at the moment though unfortunately.

Thanks for tested. I have also tested it and it looks fine, so I will merge it. please understand that Terminal contains destructive changes, but Terminal is the RC version.

**Comment by rdlabo** [comment]
released! https://github.com/capacitor-community/stripe/releases/tag/v6.4.0

**Comment by AshleyMedway** [comment]
Great effort 👍🏻

**Pull request merged**
