### PR TITLE
Deletion of repeated events in the documentation

### PR DESCRIPTION
**Pull request by tanrax**

### CODE REVIEW

**Comment by rdlabo** [comment]
Hi @tanrax . Thanks for pull request.
events in documentation is created docgen: https://github.com/capacitor-community/stripe/blob/master/package.json#L51
So this modification is always overwritten m()m

**Comment by tanrax** [comment]
Thank you for the work you do.
So there is no way to solve it?

**Comment by rdlabo** [comment]
This use https://github.com/rdlabo/capacitor-docgen/tree/release
If you can, please create pull request to this repository.

Thanks.

**Comment by tanrax** [comment]
I would love to help you, but after reading the code I can't find the problem, can anyone help?
Thanks

**Comment by rdlabo** [comment]
This is fixed. Thanks for raising probrem!!

**Pull request closed without merging**
