### PR TITLE
android: feat(terminal): add bindings for reader software update status, battery level, and simulator configuration

### PR DESCRIPTION
**Pull request by DoctorMcKay**
Adds new events to report reader software update status, an event to report reader battery status, and setSimulatorConfiguration method.

### CODE REVIEW

**Comment by kyleabens** [comment]
Any update on this?  The only thing preventing me from using this plugin is not being able to listen for firmware updates so I can convey that to the user.

**Comment by rdlabo** [comment]
Sorry for the delay. I looked it over and it is excellent! Thanks for the great pull request following the code so far.
Merge and test further.

**Comment by rdlabo** [comment]
Note: It will take some time to release the product as we will be working on the iOS implementation. Also, there is a possibility of specification changes to make it consistent with iOS behavior.

**Comment by rdlabo** [comment]
Note: iOS can't get errorCode, so change type.
https://github.com/capacitor-community/stripe/pull/375/commits/6db8444730cab2b1d7f95d9ec0fcfaf5b3ef6161

**Comment by rdlabo** [comment]
@DoctorMcKay Released! Thanks awesome pull request! https://github.com/capacitor-community/stripe/releases/tag/v6.1.0

**Comment by DoctorMcKay** [comment]
Great, thanks for the release!

I am using this in production, but it's a private app that's not publicly available.

**Pull request merged**
