### PR TITLE
allow react 18 and fix promise pending bug

### LINKED ISSUE #207: Error during initialization - Plugin does not support React 18
**Platform**

- [x] Web
- [x] iOS
- [x] Android

**Describe the bug**
After adding CapacitorStripeProvider the following error is thrown:

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

**To Reproduce**
Error is directly thrown in initialization, no additional steps necessary.

**Expected behavior**
No error is thrown.

**Additional context**
We are using React 18 and the plugin has a peer dependency on React 17, so I guess this is the problem as they seem to be incompatible.

### LINKED ISSUE #213: Stripe web stuck in fallback when upgrading to ^4.0.0
**Platform**
- [x] Web
- [ ] iOS
- [ ] Android

**Describe the bug**
After upgrading to v4.0.0+ the CapacitorStripeProvider gets stuck in fallback mode.

**To Reproduce**
1. Upgrade /demos/react project to v4 of the plugin with the accompanying upgrade to the @capacitor/* plugins to v4
2. `npm run start`
3. Open browser and observe the neverending "Loading..."

**Expected behavior**
To properly initialize the provider for the web project.

### PR DESCRIPTION
**Pull request by phal0r**
fix #207
fix #213

### CODE REVIEW

**Comment by fr3fou** [comment]
Would it be also possible to "backport" this to "3.x.x" as well? We haven't migrated to Capacitor 4 for several reasons and it will be a huge bummer if we can't use this

**Comment by phal0r** [comment]
@fr3fou I am not a maintainer, so I cannot answer this question

**Comment by rdlabo** [comment]
@phal0r  Thanks for great work, and sorry late. I will merge!!

**Comment by rdlabo** [comment]
@fr3fou No, I don't have plan. Due to the version of the Stripe SDK and other factors, we no longer recommend Capacitor3 and will not be adding any functionality to it.

**Comment by rdlabo** [comment]
@phal0r Thanks for contribute. We released v4.1.0! Please try it.
https://github.com/capacitor-community/stripe/releases/tag/v4.1.0

**Pull request merged**
