### PR TITLE
Add confirmPaymentIntent to process payments via StripeTerminal

### PR DESCRIPTION
**Pull request by yllaw**
In reference to #341 the confirmPaymentIntent is missing from the terminal payment flow. This step is needed to process payment and change the state of the PaymentIntent to `succeeded` or `requires_capture` per [the Stripe documentation](https://docs.stripe.com/terminal/payments/collect-payment?terminal-sdk-platform=ios#confirm-payment)

I have also replaced TerminalEvents.Completed in favor of TerminalEvents.CollectedPaymentIntent & TerminalEvents.ConfirmedPaymentIntent

Please code review and test. 

I have tested this on iOS (Tap to Pay on iPhone) and can confirm it works - the payment intent status changes to succeeded state

EDIT: I have also tested this on a physical Android Device (Simulated Reader since [Tap to Pay is not allowed on debuggable android applications](https://github.com/stripe/stripe-terminal-android/blob/master/CHANGELOG.md#2210---2023-06-05))

### CODE REVIEW

**Comment by yllaw** [comment]
@rdlabo Should I add the `TerminalEventsEnum.Completed` back so that it does not break existing listeners that may use that event?

I think `TerminalEventsEnum.Completed` may have to be renamed/deprecated from `StripeTerminal.collect()` method since the [end state of the terminal is to confirm payment intent](https://docs.stripe.com/terminal/payments/collect-payment?terminal-sdk-platform=ios#confirm-payment)

**Comment by rdlabo** [comment]
thanks for the great work.

> Should I add the TerminalEventsEnum.Completed back so that it does not break existing listeners that may use that event?

It should be necessary, but this time I will remove Completed to clearly communicate that the process itself has changed. So it is fine as it is!

**Comment by rdlabo** [comment]
Looks good and will be merged.

**Comment by rdlabo** [comment]
released @capacitor-community/stripe-terminal@5.5.0-beta.0

I will be testing on the device by the end of this week and will officially release it.

**Comment by yllaw** [comment]
After some research I found that Tap to Pay on Android does not work on Android 14 devices. The Stripe Terminal SDK in the android build.gradle [needs to be updated to at least 3.2.+](https://github.com/stripe/stripe-terminal-android/issues/387#issuecomment-1862215236)

On my end I updated the Stripe Terminal SDK (core & local-mobile modules) to 3.4. I have tested this on my end on a physical device and was able to use Tap to Pay on Android (without having to simulate the reader connection)

However when running `npm run verify` I get a build error:

```
> Task :capacitor-android:compileDebugJavaWithJavac
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :capacitor-android:compileReleaseJavaWithJavac
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :verifyReleaseResources FAILED

> Task :compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR: /Users/marco/Documents/repos/capacitor-community-stripe/packages/terminal/android/build/intermediates/merged_res/release/values-v34/values-v34.xml:3: AAPT: error: resource android:color/system_background_dark not found.
         
     ERROR: /Users/marco/Documents/repos/capacitor-community-stripe/packages/terminal/android/build/intermediates/merged_res/release/values-v34/values-v34.xml:4: AAPT: error: resource android:color/system_error_dark not found.
         
     ERROR: /Users/marco/Documents/repos/capacitor-community-stripe/packages/terminal/android/build/intermediates/merged_res/release/values-v34/values-v34.xml:5: AAPT: error: resource android:color/system_error_container_dark not found.
         
     ERROR: /Users/marco/Documents/repos/capacitor-community-stripe/packages/terminal/android/build/intermediates/merged_res/release/values-v34/values-v34.xml:6: AAPT: error: resource android:color/system_on_surface_light not found.
         
     ERROR: /Users/marco/Documents/repos/capacitor-community-stripe/packages/terminal/android/build/intermediates/merged_res/release/values-v34/values-v34.xml:7: AAPT: error: resource android:color/system_primary_light not found.
         
     ERROR: /Users/marco/Documents/repos/capacitor-community-stripe/packages/terminal/android/build/intermediates/merged_res/release/values-v34/values-v34.xml:8: AAPT: error: resource android:color/system_surface_light not found.
         
     ERROR: /Users/marco/Documents/repos/capacitor-community-stripe/packages/terminal/android/build/intermediates/merged_res/release/values-v34/values-v34.xml:9: AAPT: error: resource android:color/system_on_background_dark not found.
         
     ERROR: /Users/marco/Documents/repos/capacitor-community-stripe/packages/terminal/android/build/intermediates/merged_res/release/values-v34/values-v34.xml:10: AAPT: error: resource android:color/system_on_error_dark not found.
         
     ERROR: /Users/marco/Documents/repos/capacitor-community-stripe/packages/terminal/android/build/intermediates/merged_res/release/values-v34/values-v34.xml:11: AAPT: error: resource android:color/system_on_error_container_dark not found.
         
     ERROR: /Users/marco/Documents/repos/capacitor-community-stripe/packages/terminal/android/build/intermediates/merged_res/release/values-v34/values-v34.xml:12: AAPT: error: resource android:color/system_on_primary_dark not found.
         
     ERROR: /Users/marco/Documents/repos/capacitor-community-stripe/packages/terminal/android/build/intermediates/merged_res/release/values-v34/values-v34.xml:13: AAPT: error: resource android:color/system_on_primary_container_dark not found.
         
     ERROR: /Users/marco/Documents/repos/capacitor-community-stripe/packages/terminal/android/build/intermediates/merged_res/release/values-v34/values-v34.xml:14: AAPT: error: resource android:color/system_on_secondary_dark not found.
         
     ERROR: /Users/marco/Documents/repos/capacitor-community-stripe/packages/terminal/android/build/intermediates/merged_res/release/values-v34/values-v34.xml:15: AAPT: error: resource android:color/system_on_secondary_container_dark not found.
         
     ERROR: /Users/marco/Documents/repos/capacitor-community-stripe/packages/terminal/android/build/intermediates/merged_res/release/values-v34/values-v34.xml:16: AAPT: error: resource android:color/system_on_surface_dark not found.
         
     ERROR: /Users/marco/Documents/repos/capacitor-community-stripe/packages/terminal/android/build/intermediates/merged_res/release/values-v34/values-v34.xml:17: AAPT: error: resource android:color/system_on_surface_variant_dark not found.
         
     ERROR: /Users/marco/Documents/repos/capacitor-community-stripe/packages/terminal/android/build/intermediates/merged_res/release/values-v34/values-v34.xml:18: AAPT: error: resource android:color/system_on_tertiary_dark not found.
         
     ERROR: /Users/marco/Documents/repos/capacitor-community-stripe/packages/terminal/android/build/intermediates/merged_res/release/values-v34/values-v34.xml:19: AAPT: error: resource android:color/system_on_tertiary_container_dark not found.
         
     ERROR: /Users/marco/Documents/repos/capacitor-community-stripe/packages/terminal/android/build/intermediates/merged_res/release/values-v34/values-v34.xml:20: AAPT: error: resource android:color/system_outline_dark not found.
         
     ERROR: /Users/marco/Documents/repos/capacitor-community-stripe/packages/terminal/android/build/intermediates/merged_res/release/values-v34/values-v34.xml:21: AAPT: error: resource android:color/system_outline_variant_dark not found.
         
     ERROR: /Users/marco/Documents/repos/capacitor-community-stripe/packages/terminal/android/build/intermediates/merged_res/release/values-v34/values-v34.xml:22: AAPT: error: resource android:color/system_primary_dark not found.
``` 

Could this be because of Android API 34 support?

**Comment by rdlabo** [comment]
> https://github.com/stripe/stripe-terminal-android/issues/387#issuecomment-1862215236

@yllaw The plugin specifies the Terminal SDK as '3.3.+'.  https://github.com/capacitor-community/stripe/blob/main/packages/terminal/android/build.gradle#L10C1-L10C135

The next update will update it to '3.4.+', so this does not seem to be a problem. There was a breaking change in 3.4.0, which may be the reason for such an error. This will be addressed in the plugin itself.

**Comment by rdlabo** [comment]
A version with the method `collect` changed to `collectPaymentMethod` is created at https://github.com/capacitor-community/stripe/pull/344 . Try it here.

**Pull request merged**
